### ISSUE TITLE
Pipeline yaml example spinning up https://github.com/chromedp/docker-headless-shell to run headless ATF UI Tests

### ISSUE THREAD

**Issue by chiarng** [ServiceNow/sncicd_githubworkflow#2]
Today, when ATF UI Tests run, they need a Scheduled Client Test Runner opened in a browser tab/window somewhere. This is annoying for automated pipelines, for obvious reasons. One way to address this would be to have a Scheduled Client Test Runner for the target instance running, either persistently or ephemerally (on-demand from pipeline build). 

We could use https://github.com/chromedp/docker-headless-shell and provide another example yaml file.

**Comment by antonemking** [comment]
Hi @chiarnglin is this issue still valid with headless browser capability in SD [Headless Browser](https://docs.servicenow.com/bundle/sandiego-application-development/page/administer/auto-test-framework/concept/headless-browser-procedure-linux.html) ? I Have yet to try but I can confirm in a week or so when I get some free time.

**Comment by chiarng** [comment]
ATF headless browser solves this issue, difference being rather than the pipeline script initiating the docker engine call to run a container, the SN instance does it when no existing scheduled client test runner is detected upon execution of an ATF UI test.
