### ISSUE TITLE
Apply Changes from Source Control is not working as expected

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd_githubworkflow#4]
**Apply Changes from Source Control** is not working as expected. On Flow Designer and Azure Task I have used ‘Apply Changes from Source Control’ and it updated the ServiceNow instance configured as Target Instance with code from the branch assigned to the branch input. For example, both these actions had TEST as Target Instance and DEV as the branch name. However, the equivalent GitHub Action doesn’t seem to operate the same way. 

Based on sample workflow provided in the repo, I configured SNOW_SOURCE_INSTANCE with the TEST instance domain name and it didn’t get updated with code from source control. When we are applying changed from Source Control to a ServiceNow Instance, shouldn't the latter be called SNOW_TARGET_INSTANCE? Also, I didn’t see an input option for source control branch.

**Comment by chiarng** [comment]
moving Issue to the right repo :) 
https://github.com/ServiceNow/sncicd-apply-changes/issues/2
