### ISSUE TITLE
workflow_batch_install.yml  provided in Readme points to a wrong file

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd_githubworkflow#8]
Hi, 

The workflow_batch_install.yml provided under Description of workflow templates in the Readme file points to a instance_scan.yml. Can you please share the yaml file for batch install?

Thanks
Ramya

**Comment by ramyaramdasan** [comment]
Sorry, I found the yaml snippet below. Thanks.

**Comment by chiarng** [comment]
glad you found it, and no worries!
